import "./globals.css";
import NextAuthSessionProvider from "../providers/sessionProvider";
import { ReactNode } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import CustomAppBar from "@/app/components/ui/AppBar";
import CustomDrawer from "@/app/components/ui/Drawer";
import Footer from "@/app/components/ui/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Amiri:wght@400&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="font-iransans text-[13px]">
        {/* Toast notification container */}
        <ToastContainer position="top-right" autoClose={3000} />

        <NextAuthSessionProvider>
          {/* Layout wrapper */}
          <div className="flex flex-col h-screen">
            {/* AppBar */}
            <CustomAppBar />

            <div className="flex flex-1">
              {/* Sidebar */}

              {/* Main Content */}
              <div className="flex-1 overflow-auto">
              {children}
              </div>
            </div>

            {/* Footer */}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
